name: Latest blog 
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: beb77/blog-post-workflow@master
        with:
          max_post_count: "4"
          feed_list: "https://dev.to/feed/beb777"
